### ISSUE TITLE
Deleting a post crashes /index

### ISSUE THREAD

**Issue by dternyak** [dirtycoder/dirtyblog#6]
Hello,

I am building out on your existing functionality, and have just finished. Will be open sourcing soon (days).

I spent hours on a DS_Store bug, seemingly any created post is being cached, and it is very difficult to get the app working once you remove a post. 

Similarly, posts cannot be edited, due to this caching.

I would appreciate some links so I can understand how the caching is working, I can't seem to understand where the cache is being kept.

**Comment by dirtycoder** [comment]
Hi!

Did you restart the app after deleting the post?

**Comment by dternyak** [comment]
Yup. 

It should work the same on yours, you can see that it crashes. It something with that cache you are using in the models.py. I can fix it by gitignoring DS_Store and then syncing, and recloning from github. 

Hopefully that helps.

Going to open source a login system that adds posts today.

**Comment by dirtycoder** [comment]
That "cache" is only on memory, I add the Posts to a list so I only need to 'walk' the filesystem one time.

I think DS_store is a Mac OS file format, right?
If it's the responsible for the bug you are encountering it will be a bit tricky for me to reproduce it, as I'm a Linux user.

But thank you for reporting it, I'll be doing some research later.

Cool! :)
I'll implement a preview markdown editor, but for local edition only as I use git to deploy it.
There's already a branch for it here, but I run out of time at the moment. 

:warning: 
If you are using it on Heroku like me, you need extra caution because the filesystem are not persisted so every post added by the web interface not commited to git will be lost.

**Comment by dirtycoder** [comment]
@dternyak can you download from master branch and try to reproduce it again?

Thanks!

**Comment by dirtycoder** [comment]
Reopening if necessary.
